### ISSUE TITLE
update to Go 1.19

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#362]
Go 1.19 was released yesterday: https://go.dev/blog/go1.19 🎉

This means we can update CI to use Go 1.18 and 1.19, and drop 1.17, which means we can (finally!) make use of generics!

As far as I can see, these are the steps we need to take:
- [x] update Go version in workflow files
- [x] update staticcheck (open question: will there be a Go 1.19 update?)
- [x] update Codecov Action (because as we all know, uploading a code coverage file is one of the hard problems in computer science)
- [x] include https://github.com/protocol/.github/pull/353, which uses the `-shuffle` flag on `go test` (it's already merged into `next`)

Did I forget anything?

**Comment by aschmahmann** [comment]
Note that generally speaking we wait for 1.X.1 given 1.X tends to have a pile of bugs. That being said it's probably fine to update CI at 1.X as long as the binaries that want it be more careful (e.g. kubo or anything built via https://github.com/ipfs/distributions) keep deploying with 1.X-1.Latest.

**Comment by marten-seemann** [comment]
@aschmahmann Since Unified CI is only dealing with tests (and not deployments / builds), this shouldn’t have any effect on kubo at all, right? And since we’re always testing the latest two Go versions, the Go version you’re using for releasing would still be tested (even assuming that kubo was using Unified CI, which I thought it isn’t yet?).

**Comment by galargh** [comment]
Linking https://github.com/protocol/.github/issues/317 as a template for how to perform a release.

#### TODOs breakdown

###### Codecov

The newest release of codecov action is still `3.1.0`. 

Let's go ahead with https://github.com/protocol/.github/pull/340 for this then. 

Their second comment here https://github.com/codecov/codecov-action/issues/745#issuecomment-1139083047 happened after testing in https://github.com/libp2p/go-libp2p/pull/1558 so there's a chance that `3.1.0` will resolve the issue for us.

###### staticcheck

I haven't seen any chatter on this beyond https://github.com/dominikh/go-tools/issues/1306

Maybe the latest version already works with Go 1.19? We'll need to check this out.

###### update Go version in workflow files

I'll try to prepare this tomorrow.

#### Timeline

I think I should be able to prepare the following by the end of this week:
- merge https://github.com/protocol/.github/pull/340
- prepare PR updating Go version in uCI workflows
- prepare PR upgrading staticcheck
- try out statichceck with Go 1.19 in a couple of repos
- prepare release announcement

Maybe I could also modify the `deploy` workflow here so that you can opt-in to early updates from `next`. That way you would be able to get early access to Go 1.19 support and the auto-upgrades wouldn't roll it back for you. I think that should be doable by the end of week but I haven't given it too much thought yet.

As for the rest of the timeline, I think we need check if we can keep using `staticcheck` as is first. 

I'm off for vacations (8th-22nd) this month (between 15th-19th I might be around for a bit though).

**Comment by galargh** [comment]
@laurentsenta In the spirit of knowledge sharing, let's do this one together.

**Comment by galargh** [comment]
I prepared the plan for the upcoming release in https://github.com/protocol/.github/pull/366

If you want to get the update from `next` ahead of schedule, you can follow [this guide on technical previews in uCI](https://github.com/protocol/.github#technical-preview).
